#!/usr/bin/env bash

inputdir="$( realpath "${1}" )"
outdir="$( realpath "${2}" )"
DRYRUN="${3:-false}"

_dryrun() {
    [[ "${DRYRUN}" =~ "dryrun" ]] && return 0 || return 1
}

find "${inputdir}" -name "*.flac" -print0 | \
    while read -r -d $'\0' filepath
    do
        ## handle recursive directories
        fout_relative_path="$( realpath "${filepath}" --relative-to="${inputdir}" )"
        fout_path="${outdir}/${fout_relative_path}"
        fout_dir="$( dirname "${fout_path}" )"
        [[ ! -d "${fout_dir}" ]] && mkdir -p "${fout_dir}"
        if ( _dryrun ); then
            echo "${filepath} ➜ ${fout_path}"
        else
            flac --best --no-preserve-modtime -o "${fout_path}" "${filepath}"
        fi
    done
