#!/usr/bin/env bash
#

albumpath="$( realpath "${1}" )"
albumname="$( basename "${albumpath}" )"

_scrape_albumname() {
    local tagfile
    local album
    tagfile="${1}"
    # read all possible album names from ALBUM= or Album= tag
    # and save in array
    readarray -t albums < <(grep -i "ALBUM=" "${tagfile}" | cut -f2 -d"=" | sort | uniq)
    # find the longest common prefix of all strings
    # https://stackoverflow.com/q/6973088/741734
    album="$( printf "%s\n" "${albums[@]}" | sed -e '$!{N;s/^\(.*\).*\n\1.*$/\1\n\1/;D;}' )"
    #printf "%s\n" "${albums[@]}" | grep -zoP '^(.*)(?=.*?\n\1)'
    echo "${album}"
}

_scrape_year() {
    local tagfile
    local year
    tagfile="${1}"
    readarray -t years < <( grep -iE '^(date|year)=(19|20)[0-9]{2}' "${tempfile}" | cut -f2 -d"=" | sort | uniq )
    year="$( printf "%s\n" "${years[@]}" | sed -e '$!{N;s/^\(.*\).*\n\1.*$/\1\n\1/;D;}' )"
    echo "${year}"
}

_scrape_mediainfo() {
    local albumpath
    local mediainfo_output_string
    albumpath="${1}"
    mediainfo_output_string="${2}"
    readarray -t infoarray < <(find "${albumpath}" -type f -exec bash -c '\
                                 [[ "$( file -bi "$1" )" == *audio* ]]' bash {} \; -print0 | \
                                 xargs -0 -I{} mediainfo --Output="${mediainfo_output_string}" {} | sort | uniq)
    echo ${infoarray[@]}
    if [[ "${#infoarray[@]}" == 0 ]]; then 
        echo "Error"
    elif [[ "${#infoarray[@]}" == 1 ]]; then
        echo "${infoarray[1]}"
    else
        echo "Mixed"
    fi
}


tempfile="$( mktemp -t common_tags.XXXXXX )"
trap "rm -f \"${tempfile}\"" EXIT INT QUIT TERM
redflac -f "${albumpath}" --show-tags -r --common-only --no-fancy > "${tempfile}"
m_album="$( _scrape_albumname "${tempfile}" )"
m_year="$( _scrape_year "${tempfile}" )"
m_format="$( _scrape_mediainfo "${albumpath}" "Audio;%Format%" )"
m_bitdepth="$( _scrape_mediainfo "${albumpath}" "Audio;%BitDepth%" )"
m_samplingrate="$( _scrape_mediainfo "${albumpath}" "Audio;%SamplingRate%" )"

m_quality=""
[[ ! -z ${m_bitdepth} ]] && m_quality="${m_bitdepth}b"
if [[ ! -z "${m_samplingrate}" ]]; then
    m_samplingrate_k=$( echo "${m_samplingrate}" | awk '{ printf "%g", $1/1000}' )
    [[ ! -z ${m_samplingrate_k} ]] && m_quality="${m_quality}-${m_samplingrate_k}kHz"
fi


# format name
# mediainfo --Output="Audio;%Format%"
# bit depth (number only)
# mediainfo --Output="Audio;%BitDepth%"
# sampling rate (in Hz)
# mediainfo --Output="Audio;%SamplingRate%"

if [[ ! -z "${m_album}" ]]; then
    m_albumname="${m_album}"
    [[ ! -z "${m_year}" ]] && m_albumname="${m_albumname} (${m_year})"
    [[ ! -z "${m_format}" ]] && m_albumname="${m_albumname} - ${m_format}"
    [[ ! -z "${m_quality}" ]] && m_albumname="${m_albumname} {${m_quality}}"
    echo "${m_albumname}"
fi

rm -f "${tempfile}"
