#!/usr/bin/env bash

LOGFILE="/media/sdt/banskt/usr/log/btnfeed/update.log"
source /media/sdt/banskt/.bashrc
micromamba activate py311
sleep 2
python usr/apps/btn-automagic/fetch-btn-feed.py >> ${LOGFILE} 2>&1
exitcode="$?"
[[ "${exitcode}" == 0 ]] && echo "btnfeed: $( date ) | Update successful" || echo "btnfeed: $( date ) | ERROR"
exit ${exitcode}
