#!/usr/bin/env bash

shopt -s expand_aliases
source "${HOME}/.bashrc"
source "${HOME}/usr/scripts/rtcontrol-helpers.sh"

# logfiles
logdir="${HOME}/usr/log/housekeeping/$( date +"%Y-%m-%d" )"
mkdir -p "${logdir}"
unregistered_logfile="${logdir}/remove-unregistered.log"
orphan_logfile="${logdir}/remove-orphan.log"

# rTorrent session backup file
session_bakfile="${HOME}/usr/backup/rtorrent.session/rtsession.backup.$( date +'%Y.%m.%d-%H%M' ).tgz"
rtxmlrpc -q session.save
tar cfz "${session_bakfile}" $( echo $(rtxmlrpc session.path)/ | tr -s / / )*.torrent*

# Delete unregistered torrents
rt-error --delete --yes >> "${unregistered_logfile}" 2>&1

# Delete orphan data from disk
tgtdir1="${HOME}/uploads/btn-packs"
tgtdir2="${HOME}/uploads/btn-episodes"
tgtdir3="${HOME}/downloads/btn-packs"
tgtdir4="${HOME}/downloads/btn-spam"
for tgt in "${tgtdir1}" "${tgtdir2}" "${tgtdir3}" "${tgtdir4}"; do
    rt-orphan "${tgt}" | while read -r -d$'\n' fpath;
    do
        echo "${fpath}" >> "${orphan_logfile}"
        rm -rf "${fpath}"
    done
done

# send files from spam and btn-packs
# feral2ashwini all btn-packs BTNarXiv-$( date +"%Y-%m-%d" )
# feral2ashwini inactive btn-spam BTNspam-$( date +"%Y-%m-%d" )
