# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# Always load these functions and alias
if [ -f ~/.bashd/common.bashrc ]; then 
    . ~/.bashd/common.bashrc
fi

# Load login specific utilities
if shopt -q login_shell; then
    if [ -f ~/.bashd/login.bashrc ]; then
        . ~/.bashd/login.bashrc
    fi
fi

# If not running interactively, do not load interactive functions
case $- in
    *i*) ;;
      *) return ;;
esac
if [ -f ~/.bashd/interactive.bashrc ]; then
    . ~/.bashd/interactive.bashrc
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
