# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export DOTFILES=~/.dotfiles

_log_debug() { [[ ${DOTDEBUG} == 0 ]] && echo "${@}"; }

# source one file or all files in one directory, recursively
# use like so:
#   dotsrc <filename>
#   dotsrc <directory>
dotsrc() {
    local file
    if [ -d ${1} ]; then
        _log_debug "Loading ${1} directory"
        for file in ${1}/*; do
            _log_debug "File found: ${file}"
            dotsrc ${file}
        done
    fi
    if [ -f ${1} ]; then
        _log_debug "Loading file ${1}"
        source ${1}
    fi
}

loadbashrc() { 
    _log_debug "Bash: Loading ${1} utilities from ${DOTFILES}/bash/${1}.bashrc"
    dotsrc ${DOTFILES}/bash/${1}.bashrc; 
}

# load custom environment variable before doing anything
if [[ -f ${HOME}/.custom_dotfiles/bashrc ]]; then
    dotsrc ${HOME}/.custom_dotfiles/bashrc
fi

[[ -z ${DOTDEBUG} ]] && DOTDEBUG=1

# Common initialization
loadbashrc common

# Load login specific utilities
if shopt -q login_shell; then
    loadbashrc login
fi

# If not running interactively, do not load interactive functions
case $- in
    *i*) ;;
      *) return ;;
esac
loadbashrc interactive

## # >>> conda initialize >>>
## # !! Contents within this block are managed by 'conda init' !!
## __conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
## if [ $? -eq 0 ]; then
##     eval "$__conda_setup"
## else
##     if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
##         . "/opt/miniconda3/etc/profile.d/conda.sh"
##     else
##         export PATH="/opt/miniconda3/bin:$PATH"
##     fi
## fi
## unset __conda_setup
## # <<< conda initialize <<<
