#!/usr/bin/env bash

shopt -s expand_aliases
source "${HOME}/.bashrc"
source "${HOME}/.custom_dotfiles/rtcontrol-helpers.sh"

# logfiles
logdir="${HOME}/local/etc/housekeeping/logs/$( date +"%Y-%m-%d" )"
mkdir -p "${logdir}"
unregistered_logfile="${logdir}/remove-unregistered.log"
orphan_logfile="${logdir}/remove-orphan.log"

# rTorrent session backup file
session_bakfile="${HOME}/data/backup/rtorrent.session/rtsession.backup.$( date +'%Y.%m.%d-%H%M' ).tgz"
rtxmlrpc -q session.save
tar cfz "${session_bakfile}" $( echo $(rtxmlrpc session.path)/ | tr -s / / )*.torrent*

rt-error --delete --yes >> "${unregistered_logfile}" 2>&1

tgtdir1="${HOME}/data/media.library/btn-archive"
tgtdir2="${HOME}/data/downloads/btn-spam"
for tgt in "${tgtdir1}" "${tgtdir2}"; do
    rt-orphan "${tgt}" | while read -r -d$'\n' fpath;
    do
        echo "${fpath}" >> "${orphan_logfile}"
        rm -rf "${fpath}"
    done
done
